### ISSUE TITLE
Minor Issue

### ISSUE THREAD

**Issue by GabrielGrimberg** [yungrazr/OOP_Assignment2#2]
Greetings Daniel, I remember you saying that you will be making a clone of RuneScape, although you are making something different, may I know why you changed your idea?

Regards,

Gabriel.

**Comment by yungrazr** [comment]
Thank you for your inquiry Gabriel, 
the RuneScape clone will be a different project of mine, to be announced soon. 
I will let you know how it progresses. 
Hope you can enjoy this breakout game in the meantime :)
